joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

wiper_joint_velocity_controller:
  type: effort_controllers/JointVelocityController
  joint: wiper_joint
  pid: {p: 0.1, i: 0.01, d: 0.01}
